<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * YewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YewRepository extends EntityRepository
{
}
